### ISSUE TITLE
是否可以调用本地ollama接口

### ISSUE THREAD

**Issue by wibur0620** [heshengtao/comfyui_LLM_party#10]
如果可以的话就太棒了，ollama管理模型，这应该是可以做到的，像comfyui ollama插件就是调用ollama的接口在comfyui中使用llm

**Comment by heshengtao** [comment]
我没有试过，但是理论上是可以的，因为只要是openai格式的api接口就可以用，我用了很多包装成openai的各类模型的中转key，都是可以正常使用的。如果你尝试了有问题，请告诉我，如果没有问题也请告诉我，非常感谢你的建议！

**Comment by heshengtao** [comment]
请注意base_url的填写是以/V1/结尾的网址

**Comment by heshengtao** [comment]
调用ollama测试成功，你可以参考下图的参数填入，如果调用出现503，是因为科学上网没有关，记得base_url最后是/v1/
<img width="943" alt="调用ollama" src="https://github.com/heshengtao/comfyui_LLM_party/assets/20573295/ec23d104-1ba8-4b30-99a8-53a6f3df77b4">
