### ISSUE TITLE
Error on install: missing escape characters in filepaths

### ISSUE THREAD

**Issue by Jonseed** [heshengtao/comfyui_LLM_party#106]
**Describe the bug**
I installed LLM party, and got this error in the terminal:
```
D:\repos\ComfyUI\custom_nodes\comfyui_LLM_party\custom_tool\feishu_send_msg.py:290: SyntaxWarning: invalid escape sequence '\o'
  file_path="D:\\aaaCode\\feishu\output\9c809373e1f617e1e2e3a5dc39adc0ed_8399068463954610687.jpg",
D:\repos\ComfyUI\custom_nodes\comfyui_LLM_party\custom_tool\feishu_send_msg.py:292: SyntaxWarning: invalid escape sequence '\o'
  feishu.send_msg(msg_type="audio", file_path="D:\\aaaCode\\feishu\output\\audio.wav")
```

Looks like there are missing escape backslashes in the filepaths before \output

**To Reproduce**
1. Install LLM party with ComfyUI Manager
2. Restart ComfyUI.
3. See terminal.

**Expected behavior**
No hardcoded files at wrong filepaths.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge Version 129.0.2792.79
 - Version: 23H2

**Additional context**

**Comment by heshengtao** [comment]
This is not a error, just a warning, it doesn't affect
