### ISSUE TITLE
Error on install: Failed to install llama-cpp-python

### ISSUE THREAD

**Issue by Jonseed** [heshengtao/comfyui_LLM_party#107]
**Describe the bug**
When installing LLM party, got this error:
```
Installing llama-cpp-python...
Looking in indexes: https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/AVX2/cu121
ERROR: Could not find a version that satisfies the requirement llama-cpp-python (from versions: none)
ERROR: No matching distribution found for llama-cpp-python
Failed to install llama-cpp-python: Command '['D:\\repos\\conda-envs\\comfy\\python.exe', '-m', 'pip', 'install', 'llama-cpp-python', '--no-cache-dir', '--force-reinstall', '--no-deps', '--index-url=https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/AVX2/cu121']' returned non-zero exit status 1.
```

**To Reproduce**
1. Install LLM party
2. Restart ComfyUI
3. Look in terminal.

**Expected behavior**
Valid installation of llama-cpp-python?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge 129.0.2792.79
 - Version 23H2

**Additional context**

**Comment by Jonseed** [comment]
I tried re-installing pytorch so I was on cuda 12.4. Then I tried restarting Comfy and got this error:

```
cuda --force-reinstall --no-deps --index-url=https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/AVX2/cu122
Installing llama-cpp-python...
Looking in indexes: https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/AVX2/cu122
ERROR: Could not find a version that satisfies the requirement llama-cpp-python (from versions: none)
ERROR: No matching distribution found for llama-cpp-python
Failed to install llama-cpp-python: Command '['D:\\repos\\conda-envs\\comfy\\python.exe', '-m', 'pip', 'install', 'llama-cpp-python', '--no-cache-dir', '--force-reinstall', '--no-deps', '--index-url=https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/AVX2/cu122']' returned non-zero exit status 1.
```

**Comment by Jonseed** [comment]
I just did `pip install llama-cpp-python`, and it built the wheel and installed.

**Comment by heshengtao** [comment]
Thanks for your issue, I changed a llama-cpp-python source URL, which is being tested~

**Comment by heshengtao** [comment]
After the test is completed, I installed party on the latest version of comfyui and successfully installed the cuda124 version of llama-cpp-python. It seems that there is still a problem with the previous source URL.
