### ISSUE TITLE
in API mode, ShowTextNode cause an Error: extra_pnginfo[0] is not a dict or missing 'workflow' key 

### ISSUE THREAD

**Issue by shirubei** [heshengtao/comfyui_LLM_party#123]
**Describe the bug**
in API mode, an Error of "extra_pnginfo[0] is not a dict or missing 'workflow' key " displayed on the command line log.
I'm sure it was caused by ShowTextNode.

**To Reproduce**
1. start up comfyui
2. open a cmd line window
3.  go to ComfyUI\ComfyUI>
4. run  ..\python_embeded\python flux_dev_api_calling.py
[flux_dev_api_calling.zip](https://github.com/user-attachments/files/17619900/flux_dev_api_calling.zip)
5. See error of screenshot

**Expected behavior**
No error message.

**Screenshots**
![image](https://github.com/user-attachments/assets/f46190fc-47ca-47a9-a56c-b13bfeb9da73)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome(should have nothing to do with the bug cause the PG is run on cmd line)
 - Version 130.0.6723.70

**Additional context**
on error message in interactive mode(run workflow in Chrome)

**Comment by shirubei** [comment]
Btw, added "--changed" in comfyui_LLM_party\tools\show_text.py to make sure it's the right script that caused the error.

**Comment by heshengtao** [comment]
When there is no front end, this error will be reported, but it will not affect the operation. If you can't run it, it's another problem. Besides, it doesn't make any sense to display text nodes when calling the API.
