### ISSUE TITLE
 "browser_use"  requirement need python>=3.11

### ISSUE THREAD

**Issue by Pythonpa** [heshengtao/comfyui_LLM_party#133]
After the new upgrade, there is a dependency called `browser_use`, which requires that the python version must be equal to or greater than `3.11`, resulting in a large number of comfyui based on `python=3.10` or lower, which will prompt the environment installation failure **every time** it starts.

**Comment by heshengtao** [comment]
The lack of this dependency will only affect the loading of the browser's automatic control tool node, and there will be no other problems. This is just a reminder that some nodes are not loaded. Don't use this node to worry about it.

**Comment by Pythonpa** [comment]
ok ,got it
