### ISSUE TITLE
请求帮助，插件启动失败

### ISSUE THREAD

**Issue by uooyeee** [heshengtao/comfyui_LLM_party#135]
<img width="1313" alt="截屏2024-12-22 20 03 53" src="https://github.com/user-attachments/assets/5f75db30-b39a-4f1a-ae9a-048dc96f5185" />
正常通过ComfyUI-Manager安装插件

**Comment by uooyeee** [comment]
运行 python -X faulthandler main.py的结果
<img width="1313" alt="截屏2024-12-22 20 06 38" src="https://github.com/user-attachments/assets/f4dce2b0-6a12-46fb-a950-a72b934f1d0f" />
<img width="1313" alt="截屏2024-12-22 20 07 25" src="https://github.com/user-attachments/assets/7a8590c9-da39-4114-8587-820fbc8a7e50" />

**Comment by uooyeee** [comment]
系统版本：macos sequoia 15.1.1

**Comment by uooyeee** [comment]
> 是插件整个不能启动，还是只是有部分节点缺失，还是comfyui都不能启动呢

装上后comfyui都不能启动，删除插件后正常

**Comment by heshengtao** [comment]
那可能M2芯片不支持一些依赖，所以装不上，我这里只有M3芯片的设备，也没有办法验证我的猜想，我的M3芯片的两台电脑都是可以的

**Comment by uooyeee** [comment]
> 那可能M2芯片不支持一些依赖，所以装不上，我这里只有M3芯片的设备，也没有办法验证我的猜想，我的M3芯片的两台电脑都是可以的

可否用我的设备来验证一下，不过我在新创建的用户中启动comfyui时报错 不过可以忽视

**Comment by heshengtao** [comment]
很多mac用户用M1 M2芯片的，都有这个未知的内存相关的错误，估计就是有依赖没有适配M芯片的内存，我也研究不出来，我已经研究过很久了，这个问题我解决不了，MAC搞AI还是太多坑了

**Comment by uooyeee** [comment]
> 很多mac用户用M1 M2芯片的，都有这个未知的内存相关的错误，估计就是有依赖没有适配M芯片的内存，我也研究不出来，我已经研究过很久了，这个问题我解决不了，MAC搞AI还是太多坑了

好的，感谢回答
