### ISSUE TITLE
Feature Request: LangChainDeprecationWarning and Requirements

### ISSUE THREAD

**Issue by zmwv823** [heshengtao/comfyui_LLM_party#14]
## 1、LangChainDeprecationWarning:  tools/(wikipedia.py & load_ebd.py & check_web.py)
```
LangChainDeprecationWarning: Importing HuggingFaceBgeEmbeddings from langchain.embeddings is deprecated. Please replace deprecated imports:

>> from langchain.embeddings import HuggingFaceBgeEmbeddings

with new imports of:

>> from langchain_community.embeddings import HuggingFaceBgeEmbeddings
```
- a: from langchain.embeddings import HuggingFaceBgeEmbeddings
- b: from langchain_community.embeddings import HuggingFaceBgeEmbeddings

If with b will make the results different or bad results.
## 2、Maybe we should not check and install python module when starting comfyui:
- We can install maually by using requirements.txt with cmd or terminal.

**Comment by heshengtao** [comment]
I have already fixed the LangChainDeprecationWarning error, and I greatly appreciate your suggestion. Regarding your second point, some of the functions I call during installation and initialization are necessary under the circumstances. The install_llama function is used to select the appropriate llama_cpp_python based on the current running device. If it were listed in requirements.txt, directly letting pip install llama_cpp_python would result in errors for the majority of users. The check_and_uninstall_websocket function prevents conflicts between the websocket library and the websocket-client library. If your device has both websocket-client and websocket, running code that calls the comfyui API will result in errors. This function checks if websocket exists, and if so, it will uninstall both websocket-client and websocket, then reinstall websocket-client. The vast majority of other libraries are installed via requirements.txt. If I have misunderstood your point, please do not hesitate to enlighten me! Thank you once again for your suggestion!

**Comment by heshengtao** [comment]
I removed some of the console output at startup to make the program look a bit cleaner, haha. If you can’t see it, it’s not there, hahaha.

**Comment by zmwv823** [comment]
> I removed some of the console output at startup to make the program look a bit cleaner, haha. If you can’t see it, it’s not there, hahaha.

Thanks，lol.
