### ISSUE TITLE
即使外部参数不变，大模型节点总是会运行，因为大模型对同一个问题也总是有着不同的回答。

### ISSUE THREAD

**Issue by msola-ht** [heshengtao/comfyui_LLM_party#17]
这个有办法调整一下吗

或者像随机种子那样

我外部参数不变，只运行一次就可以了

**Comment by heshengtao** [comment]
我在LLM链的节点上放了一个is_locked参数，如果开启了之后，LLM只会返回上次返回的结果，相当于跳过了这个节点，看是不是满足您的需求

**Comment by heshengtao** [comment]
需要注释掉我的项目文件夹下的llm.py文件里LLM类的694到698行：    
    @classmethod
    def IS_CHANGED(s):
        # 返回当前时间的哈希值，确保每次都不同
        current_time = str(time.time())
        return hashlib.sha256(current_time.encode()).hexdigest()
注释掉之后，只有你改变了LLM节点的输入，才会重新运行这个节点，我会去试试把这个is_locked和这函数绑定一下哈哈哈，应该就是你要的效果了

**Comment by msola-ht** [comment]
> 需要注释掉我的项目文件夹下的llm.py文件里LLM类的694到698行： @classmethod def IS_CHANGED(s): # 返回当前时间的哈希值，确保每次都不同 current_time = str(time.time()) return hashlib.sha256(current_time.encode()).hexdigest() 注释掉之后，只有你改变了LLM节点的输入，才会重新运行这个节点，我会去试试把这个is_locked和这函数绑定一下哈哈哈，应该就是你要的效果了

感谢，按大佬提供的方法修改了，这样才不参数不变，就不用每次运行了

**Comment by heshengtao** [comment]
更新了一个新的版本，最新版本里，is_locked和 IS_CHANGED函数挂钩了，现在只需要is_locked开启，就是你要的效果了，应该没有什么问题了，我把这个问题关闭了哈
