### ISSUE TITLE
非常不错的项目。能不能在此基础上，建立工作流库，实现通agent方式可以智能选择工作流执行？

### ISSUE THREAD

**Issue by foxyear-kyumin** [heshengtao/comfyui_LLM_party#18]

**Comment by heshengtao** [comment]
这个功能我去研究一下哈哈哈哈，先插个眼，Mark一下哈哈哈，应该是不难实现的

**Comment by foxyear-kyumin** [comment]
可以实现的话就很好玩，以后只要跟LLM对话就可以实现很多不同工作流的功能

**Comment by Bobbyztz** [comment]
刚接触这个项目，这条issue说的是智能选择工作流而不是工作节点（就像dify那样）是吗？（确认一下）

**Comment by heshengtao** [comment]
我好像终于完成这个issue了！！！请看这里：
https://github.com/heshengtao/comfyui_LLM_party/blob/main/README_ZH.md#%E6%9C%80%E6%96%B0%E6%9B%B4%E6%96%B0
