### ISSUE TITLE
大佬你好，除了分类器，还有什么办法可以把推出来的提示词进行分类，然后分别接入到CLIP的正负提示词里面吗

### ISSUE THREAD

**Issue by msola-ht** [heshengtao/comfyui_LLM_party#19]
我现在使用了2次API来调用

第一次是提示词润色

第二次是把润色的提示词使用分类器分类

出了这个办法还有其他的吗，整个流程只使用1次API这样

![PixPin_2024-06-10_00-00-30](https://github.com/heshengtao/comfyui_LLM_party/assets/45963567/c95f4db5-1165-492f-95b3-9d85936901e8)

**Comment by heshengtao** [comment]
<img width="1043" alt="屏幕截图 2024-06-10 100307" src="https://github.com/heshengtao/comfyui_LLM_party/assets/20573295/0adf4dee-7f7d-401b-b445-b217a2510734">
我在逻辑这个子菜单下写了一个提取字符串的节点，按如上图所示，可以截取字符串中的任意两个字符串之间的字符

**Comment by heshengtao** [comment]
是我刚才新加的节点，你可能需要更新一下才能看到哈哈哈

**Comment by heshengtao** [comment]
你这个透明质感的节点皮肤是哪个插件里的哇哈哈哈，推荐一下呀

**Comment by msola-ht** [comment]
好的，待会试试看
皮肤是easy use这个插件的

**Comment by msola-ht** [comment]
大佬，效果很好
我在你提示词模版下面限制那里加了2条：
- Positive prompt 部分以“**Positive Prompt:**”开头。
- negative prompt 部分以"**Negative Prompt:**"开头。
要不然有时候出来的提示词不带冒号

**Comment by heshengtao** [comment]
好的，我改一下hhh

**Comment by msola-ht** [comment]
大佬，另外我现在使用这个方式自定义面具的，但是每次都要输入TXT的名称，这个有办法做成列表选择吗，这样的话我丢几个进去，就不需要每次去找TXT文件名打上去，可以随时切换。
或者还有什么其他方式使用吗？
![PixPin_2024-06-10_19-40-00](https://github.com/heshengtao/comfyui_LLM_party/assets/45963567/35978c68-57a8-4c03-82d4-6dcfd46f8b60)

**Comment by heshengtao** [comment]
在面具子菜单的第一个，加载人格面具，可以列表选择，面具txt的加载路径就是...\ComfyUI\custom_nodes\comfyui_LLM_party\persona这个文件夹，我的图片生成提示词txt就放在这里

**Comment by heshengtao** [comment]
其实你可以加我的答疑Q群：931057213    那里比较方便聊，如果你要私聊，也可以从群里戳一个小窗私聊

**Comment by heshengtao** [comment]
OK，欢迎随时提问！如果有BUG需要修复或者新的功能请求也欢迎在这里问，我都会回答滴！

**Comment by CharlinChen** [comment]
请教下，生成的提示词怎么接到CLIP里呢？CLIP没有string的node啊？

**Comment by heshengtao** [comment]
右键转换组件为输入
&nbsp;


贺声涛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月9日(星期一) 下午5:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [heshengtao/comfyui_LLM_party] 大佬你好，除了分类器，还有什么办法可以把推出来的提示词进行分类，然后分别接入到CLIP的正负提示词里面吗 (Issue #19)














 
请教下，生成的提示词怎么接到CLIP里呢？CLIP没有string的node啊？
