### ISSUE TITLE
fastapi文件名与所导包的包名重名

### ISSUE THREAD

**Issue by NingZhenPeng** [heshengtao/comfyui_LLM_party#21]
问题：
按照文档 pip install -r requirements.txt 执行后 ，在comfyui也安装成功了
<img width="935" alt="1904af526d536afb31176cfdfa2771b2" src="https://github.com/heshengtao/comfyui_LLM_party/assets/19367709/382e7b41-b4c0-4d3d-a456-8701b017f512">

但是执行 fastapi.py  时提示 ImportError: cannot import name 'FastAPI' from partially initialized module 'fastapi'
<img width="368" alt="657f85f05234056fb958784e96cf0b0d" src="https://github.com/heshengtao/comfyui_LLM_party/assets/19367709/b385a99c-e77a-4a35-ad0a-102c3401b35a">

解决方法：
修改自己的 fastapi.py 名称，不要与 from fastapi import FastAPI, HTTPException,Request, Depends 导包的 fastapi 就可以了,
估计是自定义的文件名与所导包的包名重名导致

**Comment by heshengtao** [comment]
已修复！
