### ISSUE TITLE
AttributeError: 'Llava15ChatHandler' object has no attribute 'clip_ctx'

### ISSUE THREAD

**Issue by Franks001** [heshengtao/comfyui_LLM_party#22]
Using deterministic algorithms for pytorch
Total VRAM 11264 MB, total RAM 32509 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : native
VAE dtype: torch.float32
Using pytorch cross attention
Adding extra search path checkpoints E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/Stable-diffusion
Adding extra search path configs E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/Stable-diffusion
Adding extra search path vae E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/VAE
Adding extra search path loras E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/Lora
Adding extra search path loras E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/LyCORIS
Adding extra search path upscale_models E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/ESRGAN
Adding extra search path upscale_models E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/RealESRGAN
Adding extra search path upscale_models E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/SwinIR
Adding extra search path embeddings E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/embeddings
Adding extra search path hypernetworks E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/hypernetworks
Adding extra search path controlnet E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/ControlNet
Adding extra search path controlnet E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/extensions/sd-webui-controlnet/models
Adding extra search path mmdets E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/mmdets/bbox
Adding extra search path ultralytics E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/ultralytics/bbox
Adding extra search path ultralytics E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/ultralytics/segm
Adding extra search path sams E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/sams
Adding extra search path seecoders E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/seecoders
Adding extra search path deepbump E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/deepbump
Adding extra search path insightface E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/insightface
Adding extra search path face_restore E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/face_restore
Adding extra search path FILM E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/FILM

Import times for custom nodes:
   0.0 seconds: E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   6.1 seconds: E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_LLM_party

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
!!! Exception during processing!!! [WinError -529697949] Windows Error 0xe06d7363
Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_LLM_party\llm.py", line 1412, in load_llava_checkpoint
    clip = Llava15ChatHandler(clip_model_path = clip_path, verbose=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_cpp\llama_chat_format.py", line 1072, in __init__
    self.clip_ctx = self._llava_cpp.clip_model_load(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_cpp\llava_cpp.py", line 174, in clip_model_load
    return _libllava.clip_model_load(fname, verbosity)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError -529697949] Windows Error 0xe06d7363
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Prompt executed in 0.14 seconds
got prompt
!!! Exception during processing!!! [WinError -529697949] Windows Error 0xe06d7363
Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_LLM_party\llm.py", line 1412, in load_llava_checkpoint
    clip = Llava15ChatHandler(clip_model_path = clip_path, verbose=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_cpp\llama_chat_format.py", line 1072, in __init__
    self.clip_ctx = self._llava_cpp.clip_model_load(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_cpp\llava_cpp.py", line 174, in clip_model_load
    return _libllava.clip_model_load(fname, verbosity)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError -529697949] Windows Error 0xe06d7363
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Prompt executed in 0.01 seconds
Exception ignored in: <function Llava15ChatHandler.__del__ at 0x000002202AA14040>
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_cpp\llama_chat_format.py", line 1078, in __del__
    if self.clip_ctx is not None and self._clip_free is not None:
       ^^^^^^^^^^^^^
AttributeError: 'Llava15ChatHandler' object has no attribute 'clip_ctx'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by Franks001** [comment]
![image](https://github.com/heshengtao/comfyui_LLM_party/assets/130634167/e000ca61-d830-4bf7-b79e-58fd6b6fc5f8)

**Comment by heshengtao** [comment]
Please change the model path to your model folder path. For example, on my computer, the path is "D:\ AI\ mychat\ model\ llaVa\", be careful to end with "\"

**Comment by Franks001** [comment]
I have established a model path on drive E, E:\ AI\ mychat\ model\ llaVa\, Except for different drive letters, the hierarchical structure of the folder is completely consistent. Therefore, in the opened workflow, only the drive letters of the default paths for model_path and tokenizer_path have been modified, while everything else remains unchanged

**Comment by heshengtao** [comment]
![屏幕截图 2024-06-16 171724](https://github.com/heshengtao/comfyui_LLM_party/assets/20573295/f0952a3b-be24-4b18-96a3-d475e5c8a2c0)
Is your model placed in the corresponding position correctly?Download the model [here](https://huggingface.co/xtuner/llava-llama-3-8b-v1_1-gguf/tree/main)
