### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by Franks001** [heshengtao/comfyui_LLM_party#23]
Using deterministic algorithms for pytorch
Total VRAM 11264 MB, total RAM 32509 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : native
VAE dtype: torch.float32
Using pytorch cross attention
Adding extra search path checkpoints E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/Stable-diffusion
Adding extra search path configs E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/Stable-diffusion
Adding extra search path vae E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/VAE
Adding extra search path loras E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/Lora
Adding extra search path loras E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/LyCORIS
Adding extra search path upscale_models E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/ESRGAN
Adding extra search path upscale_models E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/RealESRGAN
Adding extra search path upscale_models E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/SwinIR
Adding extra search path embeddings E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/embeddings
Adding extra search path hypernetworks E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/hypernetworks
Adding extra search path controlnet E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/ControlNet
Adding extra search path controlnet E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/extensions/sd-webui-controlnet/models
Adding extra search path mmdets E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/mmdets/bbox
Adding extra search path ultralytics E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/ultralytics/bbox
Adding extra search path ultralytics E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/ultralytics/segm
Adding extra search path sams E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/sams
Adding extra search path seecoders E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/seecoders
Adding extra search path deepbump E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/deepbump
Adding extra search path insightface E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/insightface
Adding extra search path face_restore E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/face_restore
Adding extra search path FILM E:/AI/SD/webui/QiuYe/sd-webui-aki-v4.3/models/FILM

Import times for custom nodes:
   0.0 seconds: E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   6.2 seconds: E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_LLM_party

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
!!! Exception during processing!!! stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_LLM_party\llm.py", line 831, in chatbot
    self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_path, trust_remote_code=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 865, in from_pretrained
    return tokenizer_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\tokenization_utils_base.py", line 2110, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\tokenization_utils_base.py", line 2336, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\.cache\huggingface\modules\transformers_modules\tokenization_chatglm.py", line 109, in __init__
    self.tokenizer = SPTokenizer(vocab_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\.cache\huggingface\modules\transformers_modules\tokenization_chatglm.py", line 17, in __init__
    assert os.path.isfile(model_path), model_path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 30, in isfile
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Prompt executed in 0.13 seconds

**Comment by Franks001** [comment]
![image](https://github.com/heshengtao/comfyui_LLM_party/assets/130634167/975fe38f-652b-447b-ac41-106b9ba2bc52)

**Comment by heshengtao** [comment]
Please change the model path to your model folder path. For example, on my computer, the path is "D:\AI\mychat\model\chatglm3-6b\", be careful to end with "\"

**Comment by Franks001** [comment]
I have established a model path on drive E, E:\ AI\ mychat\ model\ llaVa\, Except for different drive letters, the hierarchical structure of the folder is completely consistent. Therefore, in the opened workflow, only the drive letters of the default paths for model_path and tokenizer_path have been modified, while everything else remains unchanged

**Comment by heshengtao** [comment]
The error indicates that the model_path variable should be a string, bytes, os.PathLike, or integer, but it is None. This usually means that the model file was not found at the expected location, or the path was not set correctly. Make sure you have downloaded the tokenizer model and that model_path is correctly pointing to that file. You may want to check if the path is correct and if the tokenizer model file indeed exists in the folder.

**Comment by heshengtao** [comment]
You can also directly fill in the model_path and tokenizer_path with `THUDM/chatglm3-6b`
