### ISSUE TITLE
提示出错，麻烦大佬看看怎么回事？

### ISSUE THREAD

**Issue by zhai-hello** [heshengtao/comfyui_LLM_party#25]
![03](https://github.com/heshengtao/comfyui_LLM_party/assets/150640855/99a31473-31da-4102-b6b2-02b216cb5331)
用的本地模型，提示词应该是生成好了，因为显示文本节点有显示，但是后面的 omost解码器出错了，卡住了，希望大佬看到，帮忙解决一下吧

**Comment by zhai-hello** [comment]
多运行几次，错误代码 不一样，如下面

**Comment by heshengtao** [comment]
这个是代码生成不全，说明你的max length太小了，模型的输出被截断了，就会报各种各样的错误，你可以看看你的LLM输出是不是三个点结尾，如果不是，就是被截断了

**Comment by heshengtao** [comment]
你为啥使用的是GLM模型啊，omost模型是一个被微调的llama模型，可以在这里下载：[omost-llama](https://huggingface.co/lllyasviel/omost-llama-3-8b-4bits)，说明你的LLM模型选择不对，所以无法输出正确的代码格式

**Comment by zhai-hello** [comment]
谢谢大佬，我看你b站视频了，上面用的是glm模型，以为任何模型都可以，感谢大佬回复
