### ISSUE TITLE
取消requirements.txt中包的版本限制。

### ISSUE THREAD

**Issue by ghostrunner-art** [heshengtao/comfyui_LLM_party#26]
bitsandbytes==0.43.1 
accelerate==0.30.1
playsound<=1.2.2
tenacity>=8.1.0,<8.4.0 

建议取消这类包的版本限制，直接写成
bitsandbytes
accelerate等。
如果功能有影响的话建议寻找替代方案。

这样能让更多的小伙伴无痛安装，并且以后安装其他插件时，没有后顾之忧。

十分喜欢你的插件，加油~

**Comment by heshengtao** [comment]
已修改，并且之前有固定版本的依赖项放在了requirements_fixed.txt文件中，供需要的人使用
