### ISSUE TITLE
Can't Install Requirements

### ISSUE THREAD

**Issue by tanzim5** [heshengtao/comfyui_LLM_party#31]
pip install -r requirements.txt
Requirement already satisfied: beautifulsoup4 in c:\users\tanzi\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 1)) (4.12.3)
Collecting docx2txt (from -r requirements.txt (line 2))
  Downloading docx2txt-0.8.tar.gz (2.8 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting langchain (from -r requirements.txt (line 3))
  Downloading langchain-0.2.6-py3-none-any.whl.metadata (7.0 kB)
Collecting langchain_community (from -r requirements.txt (line 4))
  Downloading langchain_community-0.2.6-py3-none-any.whl.metadata (2.5 kB)
Collecting langchain_text_splitters (from -r requirements.txt (line 5))
  Downloading langchain_text_splitters-0.2.2-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: openai in c:\users\tanzi\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 6)) (1.30.5)
Collecting openpyxl (from -r requirements.txt (line 7))
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: pandas in c:\users\tanzi\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 8)) (2.2.2)
Requirement already satisfied: pytz in c:\users\tanzi\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 9)) (2024.1)
Requirement already satisfied: Requests in c:\users\tanzi\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 10)) (2.32.2)
Collecting xlrd (from -r requirements.txt (line 11))
  Downloading xlrd-2.0.1-py2.py3-none-any.whl.metadata (3.4 kB)
Collecting faiss-cpu (from -r requirements.txt (line 12))
  Downloading faiss_cpu-1.8.0.post1-cp310-cp310-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: websocket-client in c:\users\tanzi\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 13)) (1.8.0)
Collecting streamlit (from -r requirements.txt (line 14))
  Downloading streamlit-1.36.0-py2.py3-none-any.whl.metadata (8.5 kB)
Collecting virtualenv (from -r requirements.txt (line 15))
  Downloading virtualenv-20.26.3-py3-none-any.whl.metadata (4.5 kB)
Collecting tiktoken (from -r requirements.txt (line 16))
  Downloading tiktoken-0.7.0-cp310-cp310-win_amd64.whl.metadata (6.8 kB)
Requirement already satisfied: transformers in c:\users\tanzi\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 17)) (4.41.1)
Collecting transformers_stream_generator (from -r requirements.txt (line 18))
  Downloading transformers-stream-generator-0.0.5.tar.gz (13 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting optimum (from -r requirements.txt (line 19))
  Downloading optimum-1.20.0-py3-none-any.whl.metadata (19 kB)
Collecting pdfplumber (from -r requirements.txt (line 20))
  Downloading pdfplumber-0.11.1-py3-none-any.whl.metadata (39 kB)
Collecting wikipedia (from -r requirements.txt (line 21))
  Downloading wikipedia-1.4.0.tar.gz (27 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting arxiv (from -r requirements.txt (line 22))
  Downloading arxiv-2.1.3-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: bitsandbytes in c:\users\tanzi\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 23)) (0.43.1)
Requirement already satisfied: accelerate in c:\users\tanzi\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 24)) (0.30.1)
Requirement already satisfied: fastapi in c:\users\tanzi\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 25)) (0.111.0)
Collecting py-cpuinfo (from -r requirements.txt (line 26))
  Downloading py_cpuinfo-9.0.0-py3-none-any.whl.metadata (794 bytes)
Collecting diskcache (from -r requirements.txt (line 27))
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Collecting requests_toolbelt (from -r requirements.txt (line 28))
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting playsound (from -r requirements.txt (line 29))
  Downloading playsound-1.3.0.tar.gz (7.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "c:\users\tanzi\appdata\local\programs\python\python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "c:\users\tanzi\appdata\local\programs\python\python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\users\tanzi\appdata\local\programs\python\python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\tanzi\AppData\Local\Temp\pip-build-env-u_hkwway\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\tanzi\AppData\Local\Temp\pip-build-env-u_hkwway\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\tanzi\AppData\Local\Temp\pip-build-env-u_hkwway\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\tanzi\AppData\Local\Temp\pip-build-env-u_hkwway\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "c:\users\tanzi\appdata\local\programs\python\python310\lib\inspect.py", line 1139, in getsource
          lines, lnum = getsourcelines(object)
        File "c:\users\tanzi\appdata\local\programs\python\python310\lib\inspect.py", line 1121, in getsourcelines
          lines, lnum = findsource(object)
        File "c:\users\tanzi\appdata\local\programs\python\python310\lib\inspect.py", line 958, in findsource
          raise OSError('could not get source code')
      OSError: could not get source code
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by heshengtao** [comment]
Here are the steps to resolve the issue on your Windows system:

1. **Upgrade pip, setuptools, and wheel**:
   ```bash
   pip install --upgrade pip setuptools wheel
   ```

2. **Install Microsoft Visual C++ Build Tools**:
   - Download and install the Microsoft Visual C++ Build Tools from [here](https://visualstudio.microsoft.com/visual-cpp-build-tools/). These tools include the necessary compilers for building Python packages.

3. **Use a virtual environment**:
   - Create and activate a new virtual environment to avoid dependency conflicts:
     ```bash
     python -m venv myenv
     myenv\Scripts\activate
     ```

4. **Clear pip cache**:
   - Sometimes clearing the pip cache can resolve installation issues:
     ```bash
     pip cache purge
     ```

5. **Manually install dependencies**:
   - If you know which dependencies are missing, you can manually install them. For example:
     ```bash
     pip install playsound
     ```

**Comment by heshengtao** [comment]
Playsound library has been removed, this issue is closed
