### ISSUE TITLE
ollama的调用为什么不能成功？

### ISSUE THREAD

**Issue by JosenJin** [heshengtao/comfyui_LLM_party#49]
ollama调用不能成功，为什么？

![image](https://github.com/user-attachments/assets/ad223f32-c242-46f5-93ea-e2644eac8f34)

**Comment by heshengtao** [comment]
![屏幕截图 2024-07-29 215825](https://github.com/user-attachments/assets/89e1926c-d4bf-45cb-ade0-770abda4de0b)

请尝试更新插件到最新版，然后右键fix node ，然后尝试关闭VPN，打开ollama，以上是最新版的运行情况
