### ISSUE TITLE
能不能让llama 3.1也可以使用工具？

### ISSUE THREAD

**Issue by Datou** [heshengtao/comfyui_LLM_party#50]
Error code: 400 - {'error': {'message': 'llama3.1:8b-instruct-q6_K does not support tools', 'type': 'api_error', 'param': None, 'code': None}}

ollama的新版本已经支持工具调用了。

**Comment by heshengtao** [comment]
接口返回都说了这个8B模型不支持，ollama是做了接口，但并不意味着支持所有模型，尤其是这种8B小模型有工具调用能力。没有这个能力的模型不会因为有接口就获得能力。
不过，你可以打开llm链上的is tool in sys prompt属性，我这个黑科技可以让这种8B小模型获得工具调力（但不稳定，需要限制对话轮次）
