### ISSUE TITLE
Add new tool: duckduckgo/ searXNG websearch, no API key required

### ISSUE THREAD

**Issue by FemBoxbrawl** [heshengtao/comfyui_LLM_party#51]
**Is your feature request related to a problem? Please describe.**
no, but It would be a good addition for people who do not have an API key for web search (Google, Bing)

**Describe the solution you'd like**
similar to Google or Bing Search, but no API key required (none with duckduckgo, or a URL with SearXNG

**Describe alternatives you've considered**

**Additional context**

**Comment by heshengtao** [comment]
DuckDuckGo doesn't use the API key, so I'll add it when I have time. Thanks for your recommendation.

**Comment by heshengtao** [comment]
DuckDuckGo has been supported, but I found that only when entering English can return the relevant URL, and when entering two concepts, it will not return any information, so there are still restrictions. If it is to be commercially implemented, I think the networking stability of LLM will be weaker than that of Google and bing.

**Comment by FemBoxbrawl** [comment]
That's okay, thank you for adding!
