### ISSUE TITLE
ModuleNotFoundError: No module named 'server'

### ISSUE THREAD

**Issue by austincityuwen** [heshengtao/comfyui_LLM_party#52]
## ComfyUI-Manager: EXECUTE => ['/home/Anaconda/anaconda3/envs/comfyui/bin/python', 'install.py']
[!] /home/ComfyUI/custom_nodes/comfyui_LLM_party/install.py:11: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
[!]   import pkg_resources
[!] Traceback (most recent call last):
[!]   File "/home/ComfyUI/custom_nodes/comfyui_LLM_party/install.py", line 14, in <module>
[!]     from server import PromptServer
[!] ModuleNotFoundError: No module named 'server'
install script failed: https://github.com/heshengtao/comfyui_LLM_party

安装报错，提示没有server模块，请问这个server模块是什么呢，通过pip server直接装，还是有特定的模块。

**Comment by heshengtao** [comment]
修复了，管理器和这个导入冲突了，我删除了，换了一个方式获得路径
