### ISSUE TITLE
ComfyUI启动时，能否进一步提速？

### ISSUE THREAD

**Issue by Pythonpa** [heshengtao/comfyui_LLM_party#53]
您好。观察到，在启动ComfyUI相关节点时，party节点的耗时是比较长的，不知道你们的启动是否也是这样？
![image](https://github.com/user-attachments/assets/858085a5-1c8b-4585-b04a-46d6b61681ce)

**Comment by heshengtao** [comment]
其实，我觉得这样子比较是不公平的，别人只有一个节点，而我有80个节点，我没有花费80倍的时间加载，说明我也挺快的了，不是吗哈哈哈哈

**Comment by Pythonpa** [comment]
> 其实，我觉得这样子比较是不公平的，别人只有一个节点，而我有80个节点，我没有花费80倍的时间加载，说明我也挺快的了，不是吗哈哈哈哈

哈哈也是，毕竟承载的功能不一样
