### ISSUE TITLE
使用本地模型生成提示词后，继续文生图显存不足

### ISSUE THREAD

**Issue by delcompan** [heshengtao/comfyui_LLM_party#63]
将本地模型文生图工作流，接入stable diffusion中，显存不能释放，后面文生图显存不足，或者使用共享显存，速度特别慢，能否在提示词生成完成后，将显存释放，以便文生图顺利进行

**Comment by heshengtao** [comment]
中文readme.点工作流教程 local llm那个工作流，workflow tutorial文件夹

**Comment by heshengtao** [comment]
https://github.com/heshengtao/comfyui_LLM_party/blob/main/workflow_tutorial/LLM_Party%20for%20Local%20Models.json这是示例工作流
![屏幕截图 2024-08-10 211135](https://github.com/user-attachments/assets/74590f80-ae8b-45bb-8bab-01bc43b565ae)
这个清空模型节点可以在任意位置卸载你的模型
