### ISSUE TITLE
'Chat' object has no attribute 'parameters'

### ISSUE THREAD

**Issue by davedaverave** [heshengtao/comfyui_LLM_party#65]
![Screenshot 2024-08-11 120301](https://github.com/user-attachments/assets/c791a4db-e23d-4bc0-a742-2401a2067077)
Am i doing something wrong with ollama or not using llm party correctly?

**Comment by heshengtao** [comment]
The role of ollama is to turn your local model into an API, so you use the API loader, and you also need to use the API model chain. You can refer to this workflow file.
https://github.com/heshengtao/comfyui_LLM_party/blob/main/workflow_tutorial/LLM_Party%20for%20API%20Models.json

There are sample workflows inside, https://github.com/heshengtao/comfyui_LLM_party/blob/main/workflow_tutorial/ 

There are more workflows I didn't organize https://github.com/heshengtao/comfyui_LLM_party/blob/main/workflow/
