### ISSUE TITLE
關於一些workflow更新

### ISSUE THREAD

**Issue by BertWang** [heshengtao/comfyui_LLM_party#67]
workflow 使用出現一些節點發生錯誤。
每次更新節點後，過去的一些 workflow 反而無法使用了。
-
是否可以同步針對新的節點，更新 workflow。
不然真的不太會用。
-
還請推出新的影片教學，和我們說說新的使用，謝謝。

**Comment by heshengtao** [comment]
https://github.com/heshengtao/comfyui_LLM_party/tree/main/workflow_tutorial
这文件夹是我整理好的基础工作流，之后会把整理过的工作流放在这
教程正在制作中，主要是东西太多了，而我们开源社区里一共就三个人在做事，都是副业玩玩，根本忙不过来，请您耐心等待，感谢支持

**Comment by heshengtao** [comment]
https://openart.ai/workflows/profile/comfyui_llm_party?sort=latest&tab=creation   
我们最新努力将很多整理好的工作流放到了这里，也看到了您在openart上的留言，非常感谢您一直以来的支持，这个issue应该完成他的使命了，特来关闭
