### ISSUE TITLE
Excel Parsing of info from columns

### ISSUE THREAD

**Issue by boricuapab** [heshengtao/comfyui_LLM_party#68]
**Is your feature request related to a problem? Please describe.**
How to select the prompt and suffix from column A and B from an excel sheet and concatenate them?

**Describe the solution you'd like**
When queueing a specified line and column should be concatenated into a prompt without these kinds of tokens ({}:")

ex:
{"Prompt": "deer", "Suffix": "high quality"}

Should result in:

deer, high quality

**Describe alternatives you've considered**
I've used used a few WAS nodes to do search and replace and concat, but it gets messy with alot of nodes needed

**Additional context**
Here's a gif showing what I mean

![llmpartyexcel](https://github.com/user-attachments/assets/4140eb22-137f-4223-9e26-6cf165c48b90)

**Comment by boricuapab** [comment]
All good, works with json get node

![jsonGetFix](https://github.com/user-attachments/assets/84db7694-a754-4a76-9004-681ae3aa17d8)

**Comment by boricuapab** [comment]
Actually, is it possible to pick a specific row from the excel sheet, say I want to use row 2, then later row 4, then lastly row 3?

**Comment by heshengtao** [comment]
Add a load_all attribute to this node, and then you can use json get to get any element in the large list, for example, line 0 is to enter 0
![屏幕截图 2024-08-16 141141](https://github.com/user-attachments/assets/52948705-af12-4019-bed3-588de5b68dd4)
