### ISSUE TITLE
Unable to unload ollama model after a query using keep_alive option.

### ISSUE THREAD

**Issue by Vineshg** [heshengtao/comfyui_LLM_party#71]
Ollama allows to unload the model immediately after the query using keep_live parameter as mentioned in their docs [https://github.com/ollama/ollama/blob/main/docs/faq.md](url)

`curl http://localhost:11434/api/generate -d '{"model": "llama3", "keep_alive": 0}'`

There are other parameters as well to control the model in memory. How do I use these parameters in API large language model node? I tried using extra parameters option but i got the error 
`Completions.create() got an unexpected keyword argument 'keep_alive'`

**Comment by Vineshg** [comment]
Thanks for quick response. I have 12 GB VRAM GPU. Once LLM prompt is generated I want to unload LLM model before starting to load image generation model (Flux) to save VRAM. It will be great to implement this option in LLM_party node as a lot of people have limited VRAM.

**Comment by heshengtao** [comment]
![屏幕截图 2024-08-23 160935](https://github.com/user-attachments/assets/801cf923-7409-4dc7-ac8c-a8acf4fc80f2)
Connect the workflow as shown in my image. Use the Clear Model node in any of the connections, and enable the is_ollama parameter on the Clear Model node. You will find that after using Ollama for conversation, the model is automatically unloaded from the VRAM.

**Comment by Unityisalreadybetaken** [comment]
dalao，请问这个项目是不是也可以链接koboldcpp，像ollama一样使用？

**Comment by heshengtao** [comment]
> dalao，请问这个项目是不是也可以链接koboldcpp，像ollama一样使用？

可以
