### ISSUE TITLE
模型加载器里的对话框文字不能编辑。

### ISSUE THREAD

**Issue by xueqing0622** [heshengtao/comfyui_LLM_party#73]
模型加载器里的对话框文字不能编辑。
用的是chorme，插件和comfyui均是最新，用了frontend界面。

**Comment by xueqing0622** [comment]
点击跳出来输入框后，鼠标放开马上回去，不可编辑

**Comment by heshengtao** [comment]
我测试了一下两个加载器节点，没有复现这个BUG，你试试使用Edge浏览器。只有这个节点有这个问题吗，我的其他节点以及别人的节点都不存在这个问题吗？你的系统是什么系统，什么配置呢

**Comment by xueqing0622** [comment]
我要按死鼠标，然后修改后，按enter确定才可以改

**Comment by heshengtao** [comment]
你试试fix node说不定就好，再不行，重启comfyui就能好，再不行换个浏览器说不定能好

**Comment by xueqing0622** [comment]
fix node，reload node，重启comfyui都不行， 用习惯这个浏览器了，没事，能用就行，哈哈

**Comment by xueqing0622** [comment]
主节点是可以正常输入的，就这个模型加载器不可以，奇怪
