### ISSUE TITLE
How to do RAG / how to make the embedding tool work?

### ISSUE THREAD

**Issue by FemBoxbrawl** [heshengtao/comfyui_LLM_party#78]
I am just having problems figuring out what I need to download/ what path I need to enter to make the embedding tool work.

I downloaded bge-base-v1,5.safetensors and put it in a folder, add the path in comfyui, but then I get this error. How do I make it work correctly? what do I got to do?
![Screenshot 2024-09-01 150257](https://github.com/user-attachments/assets/74fc6f03-853e-451a-bf7d-26cc5cab6195)
![Screenshot 2024-09-01 150821](https://github.com/user-attachments/assets/6a4d4ee1-5ada-496e-b353-949c6a3552c3)

# ComfyUI Error Report
## Error Details
- **Node Type:** ebd_tool
- **Exception Type:** StopIteration
- **Exception Message:** 
## Stack Trace
```
  File "D:\AI\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\AI\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\AI\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\AI\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\AI\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\comfyui_LLM_party\tools\load_ebd.py", line 81, in file
    knowledge_base = FAISS.from_texts(chunks, bge_embeddings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\AI\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\langchain_community\vectorstores\faiss.py", line 930, in from_texts
    embeddings = embedding.embed_documents(texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\AI\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\langchain_community\embeddings\huggingface.py", line 331, in embed_documents
    embeddings = self.client.encode(
                 ^^^^^^^^^^^^^^^^^^^

  File "D:\AI\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 302, in encode
    if self.device.type == "hpu" and not self.is_hpu_graph_enabled:
       ^^^^^^^^^^^

  File "D:\AI\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 1358, in device
    first_tuple = next(gen)
                  ^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.1.3-24-gb643eae
- **Arguments:** ComfyUI\main.py --disable-smart-memory --disable-cuda-malloc --fast --port 7821 --extra-model-paths-config D:\AI\SwarmUI\Data/comfy-auto-model.yaml
- **OS:** nt
- **Python Version:** 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.3.0+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4050 Laptop GPU : native
  - **Type:** cuda
  - **VRAM Total:** 6438780928
  - **VRAM Free:** 5321523200
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

**Comment by heshengtao** [comment]
Listen to your description, did you only download bge-base-v1.5.safetensors and ignore other files on HF? You need to clone the entire repository bge-base-v1.5 locally, and then fill the folder of this repository into the path parameter of the node.

**Comment by FemBoxbrawl** [comment]
> Listen to your description, did you only download bge-base-v1.5.safetensors and ignore other files on HF? You need to clone the entire repository bge-base-v1.5 locally, and then fill the folder of this repository into the path parameter of the node.

oh okay, that makes sense. I only downloaded the safetensors. I'll download the whole thing.
