### ISSUE TITLE
Ask for help: failed to enable LLM part

### ISSUE THREAD

**Issue by hanetyb** [heshengtao/comfyui_LLM_party#80]
please give some advice
my env 
-2.3.1 +cuda12.1
-linux ubantu
i already reinstall server times. seem its normal to install dependency.
it occured error as below
![1725331190362](https://github.com/user-attachments/assets/84d50265-15d2-4b77-a85b-9e14c1dae234)

**Comment by heshengtao** [comment]
Portaudio did not install successfully, please select the command line to install according to your Linux system.


### EndeavourOS / Arch Linux
```bash
pacman -Sy
pacman -S --noconfirm portaudio
```

### CentOS / Red Hat
```bash
yum update
yum install -y portaudio
```

### Fedora
```bash
dnf update
dnf install -y portaudio
```

### openSUSE
```bash
zypper refresh
zypper install -y portaudio
```

### Debian / Ubuntu
```bash
apt-get update
apt-get install -y libportaudio2 libasound-dev
```
Note that when installing, you should install it in the comfyui environment.

**Comment by hanetyb** [comment]
cool. its helped. seem it should run by sudo
