### ISSUE TITLE
It is recommended to consider accessing deepseek’s API

### ISSUE THREAD

**Issue by tanglup** [heshengtao/comfyui_LLM_party#9]

**Comment by heshengtao** [comment]
I just asked a GPT, and it said that DeepSeek’s API is consistent with OpenAI’s format. So, as long as you input DeepSeek’s API key and base URL, you can call DeepSeek. Please use a URL ending with the /v1/ format for the base URL. If you encounter any specific issues while using DeepSeek’s API, I will optimize for those issues.

**Comment by heshengtao** [comment]
Today I did a test, and it only requires entering the model name ‘deepseek-chat’, the base_url as ‘https://api.deepseek.com/v1/’, and then entering the apikey to properly call deepseek.
