### ISSUE TITLE
Using the VLM-GGFU Model Type Provides an Error or No Output

### ISSUE THREAD

**Issue by Iory1998** [heshengtao/comfyui_LLM_party#91]
**Describe the bug**
When I use the VLM-GGUF Loader node with the Local Large Language Model Node, if VLM-GGUF model type is selected, I get this error: "Prompt exceeds n_ctx: 2913 > 1024". This error occurs even after I restart comfyUI and I load the model for the first time.
When I increase the max_ctn to a higher value, I get no output at all,  "None".
When I switch the Model type to LLM-GGUF, the model works properly and I get an output as expected.
Please refer to the screenshot attached.

**To Reproduce**
Discussed above.
**Expected behavior**

**Screenshots**
![LLM Party VLM Error](https://github.com/user-attachments/assets/1b7ec965-be4b-4397-807e-c23c729cdfdf)

Check attached.
**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser : Vivaldi

**Smartphone (please complete the following information):**

**Additional context**
I am installing the latest llama.cpp with cuda 12.4 from this wheel: llama_cpp_python-0.2.90-cp310-cp310-win_amd64.whl

**Comment by heshengtao** [comment]
By increasing the max_ntx on the loader node, it is obvious that your image is too high definition, causing your input to exceed the maximum prompt word limit you set.

**Comment by Iory1998** [comment]
> By increasing the max_ntx on the loader node, it is obvious that your image is too high definition, causing your input to exceed the maximum prompt word limit you set.

I know and I explained that even when I increase the max-ntx to say 32K, the error goes away and I get no output. Also, I checked the size of the image, and no matter the size, I get the same error. I double checked!

**Comment by heshengtao** [comment]
Increase the max_ntx on the loader node, and then increase the max_length on the local LLM node, which controls the length of the conversation. If the max_length is only 512, the output must be none.

**Comment by Iory1998** [comment]
> Increase the max_ntx on the loader node, and then increase the max_length on the local LLM node, which controls the length of the conversation. If the max_length is only 512, the output must be none.

Dear @heshengtao 
As always, thank you for your prompt response. 
I am attaching a simple VLM-GGUF workflow to demonstrate the issue here. I am using this model llava-v1.6-mistral-7b.Q8_0,
And below is a screenshot of the workflow. As you can see, I don't get any output.
![image](https://github.com/user-attachments/assets/0b7f424d-0b41-4d98-9123-bad783bc5538)
![image](https://github.com/user-attachments/assets/d4a56dd1-d403-4f48-a7a7-abc33987c2b5)
Am I doing something wrong?

**Comment by heshengtao** [comment]
You may have a garbage model, please use the llava-v1.6-mistral-7b model in this link: https://huggingface.co/cjpais/llava-1.6-mistral-7b-gguf/tree/main

![image](https://github.com/user-attachments/assets/54df6d40-7ce0-4cef-9ef1-e533b7c06d47)

**Comment by Iory1998** [comment]
> You may have a garbage model, please use the llava-v1.6-mistral-7b model in this link: https://huggingface.co/cjpais/llava-1.6-mistral-7b-gguf/tree/main
> 
> ![image](https://private-user-images.githubusercontent.com/20573295/372504757-54df6d40-7ce0-4cef-9ef1-e533b7c06d47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MTY3ODAsIm5iZiI6MTcyNzgxNjQ4MCwicGF0aCI6Ii8yMDU3MzI5NS8zNzI1MDQ3NTctNTRkZjZkNDAtN2NlMC00Y2VmLTllZjEtZTUzM2I3YzA2ZDQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDIxMDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZjUzYTJmOTU0MmQ4MjY4ZDBmYTk0ZDJiYmY4MzI3NTAyYzIwODQ0NTU5N2FiMTc0NDhlNDU5NjRhZTI3YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KS19FZFFS5zdwJA-dnUFb9JzFGpSeysT7VVoWa74Nw4)

My friend, that's exactly the model I am using. Also, I want to draw your attention to 2 things:
- The models work fine for me in LM Studio, so I know that they are working fine. See Screenshot below. 
- The below error:
> WARNING: LLM_local.original_IS_CHANGED() got an unexpected keyword argument 'system_prompt'
> Prompt exceeds n_ctx: 8904 > 8192
> Prompt executed in 7.33 seconds
That happens because of the Chat history. If I disable the chat history, no output occurs unless I activate the chat history even if I choose 1 round. Is there a way to deactivate the chat?
![image](https://github.com/user-attachments/assets/5e5c8c33-fb7e-4c73-96b5-5d9cf056fa39)

**Comment by heshengtao** [comment]
I tried it, and the Q6 version works, but the Q8 version doesn't. I don't know why. The model repository doesn't label itself as adaptable to llama-cpp-python, so I think incompatibility is also possible. You can start an API with lm studio and transfer it to the party for use, which is also possible.

**Comment by Iory1998** [comment]
Thank you for your time! Keep up the good work.
Please add perplexica in the list of tools. Good luck

**Comment by xueqing0622** [comment]
一样的问题，能跑一下，后面一直都是出错，MiniCPM-V-2_6。  而且读取gguf很卡，比api卡多了。gguf不是很快的吗。
我用这个插件读取flux和SD3.5的模型都是秒读，https://github.com/city96/ComfyUI-GGUF
Prompt exceeds n_ctx: 875 > 512
读取一次后就挂了
llama_model_loader: loaded meta data with 22 key-value pairs and 339 tensors from I:\llm\gguf\MiniCPM-V-2_6-ggml-model-Q4_K_M.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = qwen2
llama_model_loader: - kv   1:                               general.name str              = model
llama_model_loader: - kv   2:                          qwen2.block_count u32              = 28
llama_model_loader: - kv   3:                       qwen2.context_length u32              = 32768
llama_model_loader: - kv   4:                     qwen2.embedding_length u32              = 3584
llama_model_loader: - kv   5:                  qwen2.feed_forward_length u32              = 18944
llama_model_loader: - kv   6:                 qwen2.attention.head_count u32              = 28
llama_model_loader: - kv   7:              qwen2.attention.head_count_kv u32              = 4
llama_model_loader: - kv   8:                       qwen2.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv   9:     qwen2.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  10:                          general.file_type u32              = 15
llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  12:                         tokenizer.ggml.pre str              = qwen2
llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,151666]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr[i32,151666]  = [3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  15:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  16:                tokenizer.ggml.bos_token_id u32              = 151644
llama_model_loader: - kv  17:                tokenizer.ggml.eos_token_id u32              = 151645
llama_model_loader: - kv  18:            tokenizer.ggml.unknown_token_id u32              = 128244
llama_model_loader: - kv  19:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  20:                    tokenizer.chat_template str              = {% for message in messages %}{% if lo...
llama_model_loader: - kv  21:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  141 tensors
llama_model_loader: - type q4_K:  169 tensors
llama_model_loader: - type q6_K:   29 tensors
llm_load_vocab: special tokens cache size = 25
llm_load_vocab: token to piece cache size = 0.9309 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = qwen2
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 151666
llm_load_print_meta: n_merges         = 151387
llm_load_print_meta: vocab_only       = 0
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 3584
llm_load_print_meta: n_layer          = 28
llm_load_print_meta: n_head           = 28
llm_load_print_meta: n_head_kv        = 4
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_swa            = 0
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 7
llm_load_print_meta: n_embd_k_gqa     = 512
llm_load_print_meta: n_embd_v_gqa     = 512
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 18944
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 2
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 1000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_ctx_orig_yarn  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: ssm_dt_b_c_rms   = 0
llm_load_print_meta: model type       = ?B
llm_load_print_meta: model ftype      = Q4_K - Medium
llm_load_print_meta: model params     = 7.61 B
llm_load_print_meta: model size       = 4.35 GiB (4.91 BPW)
llm_load_print_meta: general.name     = model
llm_load_print_meta: BOS token        = 151644 '<|im_start|>'
llm_load_print_meta: EOS token        = 151645 '<|im_end|>'
llm_load_print_meta: UNK token        = 128244 '<unk>'
llm_load_print_meta: PAD token        = 0 '!'
llm_load_print_meta: LF token         = 148848 'ÄĬ'
llm_load_print_meta: EOT token        = 151645 '<|im_end|>'
llm_load_print_meta: EOG token        = 151643 '<|endoftext|>'
llm_load_print_meta: EOG token        = 151645 '<|im_end|>'
llm_load_print_meta: max token length = 256
llm_load_tensors: ggml ctx size =    0.15 MiB
llm_load_tensors:        CPU buffer size =  4458.57 MiB
....................................................................................
llama_new_context_with_model: n_ctx      = 512
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:        CPU KV buffer size =    28.00 MiB
llama_new_context_with_model: KV self size  =   28.00 MiB, K (f16):   14.00 MiB, V (f16):   14.00 MiB
llama_new_context_with_model:        CPU  output buffer size =     0.58 MiB
llama_new_context_with_model:        CPU compute buffer size =   303.22 MiB
llama_new_context_with_model: graph nodes  = 986
llama_new_context_with_model: graph splits = 1
AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | RISCV_VECT = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 |
Model metadata: {'qwen2.attention.head_count': '28', 'general.name': 'model', 'general.architecture': 'qwen2', 'qwen2.block_count': '28', 'qwen2.context_length': '32768', 'qwen2.attention.head_count_kv': '4', 'qwen2.embedding_length': '3584', 'general.quantization_version': '2', 'tokenizer.ggml.bos_token_id': '151644', 'qwen2.feed_forward_length': '18944', 'tokenizer.ggml.padding_token_id': '0', 'qwen2.rope.freq_base': '1000000.000000', 'qwen2.attention.layer_norm_rms_epsilon': '0.000001', 'tokenizer.ggml.eos_token_id': '151645', 'general.file_type': '15', 'tokenizer.ggml.model': 'gpt2', 'tokenizer.ggml.pre': 'qwen2', 'tokenizer.ggml.unknown_token_id': '128244', 'tokenizer.chat_template': "{% for message in messages %}{% if loop.first and messages[0]['role'] != 'system' %}{{ '<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n' }}{% endif %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}"}
Available chat formats from metadata: chat_template.default
Llama.generate: 345 prefix-match hit, remaining 1 prompt tokens to eval
llama_perf_context_print:        load time =     122.85 ms
llama_perf_context_print: prompt eval time =       0.00 ms /   347 tokens (    0.00 ms per token,      inf tokens per second)
llama_perf_context_print:        eval time =       0.00 ms /    76 runs   (    0.00 ms per token,      inf tokens per second)
llama_perf_context_print:       total time =    9043.24 ms /   423 tokens
这是一个卡通风格的图像，描绘了一个有黄色大耳朵的角色，类似兔子或精灵。这个角色有蓝色的眼睛和微笑的嘴巴，穿着一件粉红色的连衣裙，双臂伸展开来，似乎在跳跃或飞舞。背景分为两部分：顶部是蓝色的天空，底部是绿色的地面。天空中有几朵白色的云彩。
这是一个卡通风格的图像，描绘了一个有黄色大耳朵的角色，类似兔子或精灵。这个角色有蓝色的眼睛和微笑的嘴巴，穿着一件粉红色的连衣裙，双臂伸展开来，似乎在跳跃或飞舞。背景分为两部分：顶部是蓝色的天空，底部是绿色的地面。天空中有几朵白色的云彩。
Prompt executed in 47.28 seconds
got prompt
WARNING: LLM_local.original_IS_CHANGED() got an unexpected keyword argument 'system_prompt'
Prompt exceeds n_ctx: 619 > 512
Prompt executed in 29.20 seconds
got prompt
WARNING: LLM_local.original_IS_CHANGED() got an unexpected keyword argument 'system_prompt'
Prompt exceeds n_ctx: 875 > 512
Prompt executed in 75.25 seconds
got prompt
WARNING: LLM_local.original_IS_CHANGED() got an unexpected keyword argument 'system_prompt'
Prompt exceeds n_ctx: 883 > 512
Prompt executed in 75.77 seconds
